set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports clk]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports sd_reset]

set_property PACKAGE_PIN U18 [get_ports SD1]
set_property PACKAGE_PIN W20 [get_ports SD2]
set_property PACKAGE_PIN V19 [get_ports SD3]
set_property PACKAGE_PIN W19 [get_ports SD4]
set_property PACKAGE_PIN T21 [get_ports SD7]
set_property PACKAGE_PIN T20 [get_ports SD8]
set_property PACKAGE_PIN T18 [get_ports SD9]
set_property IOSTANDARD LVCMOS33 [get_ports SD1]
set_property IOSTANDARD LVCMOS33 [get_ports SD2]
set_property IOSTANDARD LVCMOS33 [get_ports SD3]
set_property IOSTANDARD LVCMOS33 [get_ports SD4]
set_property IOSTANDARD LVCMOS33 [get_ports SD7]
set_property IOSTANDARD LVCMOS33 [get_ports SD8]
set_property IOSTANDARD LVCMOS33 [get_ports SD9]